engines:
  rubocop:
    enabled: true
    # ... CONFIG CONTENT ...
    checks:
      Rubocop/Rails/HasAndBelongsToMany:
        enabled: false
  brakeman:
    enabled: true
    #exclude_fingerprints:
    #- 08c185b3f764f262539a1f76997d3a89
  eslint:
    enabled: true
  csslint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - ruby
        #mass_threshold: 30
      - javascript
ratings:
  paths:
  - app/**
  - lib/**
  - "**.rb"
  - "**.go"
exclude_paths:
- db/**
- spec/**/*
- "**/vendor/**/*"
