FORMAT: 1A
HOST: http://127.0.0.1:300/

# Rehoming API

Rehoming API 文档

## Authentication [/sessions]

用户完全依赖微信系统，首次授权登录的微信用户，系统内部会自动创建一个用户。

### Create a New Session [POST]

+ Request (application/vnd.api+json)
    + Attributes
        + data (CreateSessionData, required)

+ Response 201 (application/vnd.api+json; charset=utf-8)
    + Attributes
        + data (SessionResouceObject, required)
            
## Data Structures

### CreateSessionData

+ type: `sessions` (required)
+ attributes
    + code: `0312RTRI0rMOWj22GAUI0llVRI02RTR5` (required)


### SessionResouceObject

+ id: `ea2340d68be9b6ff537be3be1fd36268` (required)
+ type: `sessions` (required)
+ attributes (Session, required)

### Session

+ `auth_token`: `eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJtb2JpbGUiOiIxODYwMDA3NjAwNyIsImV4cCI6MTQ3MDU2ODMwMX0.sSfEHuboFYtKr4D253rAgIXNukiPEsTxV7Fp77wW1Qs` (required)