FORMAT: 1A
HOST: http://127.0.0.1:300/

# Rehoming API

Rehoming API 文档

# Group Authentication

## Session Resource [/sessions]

用户完全依赖微信系统，首次授权登录的微信用户，系统内部会自动创建一个用户。

### 微信登录 [POST]
+ Request (application/vnd.api+json)
    + Attributes
        + data (CreateSessionData, required)

+ Response 201 (application/vnd.api+json; charset=utf-8)
    + Attributes
        + data (Session, required)

# Group User

## User Resource [/users/me]

当前用户的个人信息

### 获取我的个人信息 [GET]
+ Request JSON Message
    + Headers

            Authorization: `TOKEN Value`

+ Response 200 (application/vnd.api+json; charset=utf-8)
    + Attributes
        + data (User, required)

### 更新我的个人信息 [PUT]
+ Request JSON Message
    + Headers

            Authorization: `TOKEN Value`

+ Request (application/vnd.api+json)
    + Attributes
        + data (UpdateProfileData, required)


+ Response 200 (application/vnd.api+json; charset=utf-8)
    + Attributes
        + data (User, required)

## Post Resources [/posts]

### 获取我的帖子 [GET]

+ Request JSON Message
    + Headers

            Authorization: `TOKEN Value`

+ Response 200 (application/vnd.api+json; charset=utf-8)
    + Attributes
        + data (array[Post], required)

## Favorite Resources [/favorites]

### 获取我的收藏 [GET]
+ Request JSON Message
    + Headers

            Authorization: `TOKEN Value`

+ Response 200 (application/vnd.api+json; charset=utf-8)
    + Attributes
        + data (array[Post], required)

# Group Feed

## Feed Resources [/feeds]

动态列表

### 获取我的动态列表 [GET]
+ Request JSON Message
    + Headers

            Authorization: `TOKEN Value`

+ Response 200 (application/vnd.api+json; charset=utf-8)
    + Attributes
        + data (array[Feed], required)


## Feed Resource [/feeds/{feed_id}]

### 标记动态为已读 [PUT]
+ Request JSON Message
    + Headers

            Authorization: `TOKEN Value`

+ Response 200 (application/vnd.api+json; charset=utf-8)
    + Attributes
        + data (Feed, required)

## Data Structures

### BaseUser (object)
+ id: ea2340d68be9b6ff537be3be1fd36268
+ type: users

### BaseForum (object)
+ id: `f37f66fe207798521332f9a613514b15` (required)
+ type: `forums` (required)

### BaseAttachment (object)
+ id: dc01a2ff45766cb529f017a8c4ce23c7 (required)
+ type: attachments (required)

### BasePost (object)
+ id: dc01a2ff45766cb529f017a8c4ce23c7 (required)
+ type: posts (required)

### BaseFavorite (object)
+ id: dc01a2ff45766cb529f017a8c4ce23c7 (required)
+ type: posts (required)

### BaseFeed (object)
+ id: 71adf05d-711b-4e4a-aff6-9b383ebefe93 (required)
+ type: feeds (required)

### Session (object)
+ id: ea2340d68be9b6ff537be3be1fd36268
+ type: sessions
+ attributes
    + auth_token: `eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJtb2JpbGUiOiIxODYwMDA3NjAwNyIsImV4cCI6MTQ3MDU2ODMwMX0.sSfEHuboFYtKr4D253rAgIXNukiPEsTxV7Fp77wW1Qs` (string, required)

### User (object)
- Include BaseUser
+ attributes
    + headimgurl: http://www.qiniu.com/adfasdfadaf.jpg
    + nickname: 老王
    + posts_count: 4 (number, required) - 我的帖子数目
    + favorites_count: 2 (number, required) - 我的收藏数目

### Post (object)
- Include BasePost
+ attributes
    + content: `hahaha` - 内容
    + created_at: `2016-05-26T12:46:17.000Z` - 订单创建时间
    + updated_at: `2016-05-26T12:46:17.000Z` - 订单创建时间
+ relationships
    + forum
        + data (BaseForum)
    + attachments
        + data (array[BaseAttachment])
+ included (array[Forum, Attachment], required)

### Forum (object)
- Include BaseForum
+ attributes
    + name: `Free Group` - 圈子名称

### Attachment (object)
- Include BaseAttachment
+ attributes
    + category: `image` - 附件类型
    + url: `http://www.baidu.com/a.jpg` - 附件地址

### Feed (object)
- Include BaseFeed
+ attributes
    + event: 10 (number, required) - feed 类型
    + read: false (boolean, required) - 是否已读
    + forum_name: `Free Group` (required) - 所属圈子名称
    + content: hahaha (required) - 动态关联内容的正文
    + creator_nickname: Roc (required) - 动态创建者
    + creator_avatar: http://www.qiniu.com/adfasdfadaf.jpg (required) - 动态创建者头像
    + attachments (array, required)
        + (object)
            + category: `image` - 附件类型
            + url: `http://www.baidu.com/a.jpg` - 附件地址

### CreateSessionData
+ type: sessions (string, required)
+ attributes
    + code: 0312RTRI0rMOWj22GAUI0llVRI02RTR5 (string, required)

### UpdateProfileData
- Include BaseUser
+ attributes
    + headimgurl: `adfasdfadaf.jpg`
    + nickname: `老王`
