class Users::ForumPreference < ApplicationRecord
  # table name ................................................................
  self.table_name = 'user_forum_preferences'
  # extends ...................................................................
  # includes ..................................................................
  # constants .................................................................
  # relationships .............................................................
  belongs_to :user, touch: true
  belongs_to :forum
  # validations ...............................................................
  validates :forum_id, uniqueness: { scope: :user_id }
  # callbacks .................................................................
  # scopes ....................................................................
  scope :feed_allowed, -> { where(feed_allowed: true) }
  # additional config (i.e. accepts_nested_attribute_for etc...) ..............
  encrypted_id key: 'ncZVwd6xTBVjHa'
  # class methods .............................................................
  # public instance methods ...................................................
  # protected instance methods ................................................
  # private instance methods ..................................................
end
