class Forums::MembershipRequest < ActiveType::Record[Forums::Membership]
  # extends ...................................................................
  # includes ..................................................................
  # constants .................................................................
  # relationships .............................................................
  # validations ...............................................................
  validates :action, presence: true, inclusion: { in: %w(accept reject ignore) }, allow_blank: true
  # callbacks .................................................................
  before_save :auto_approval, unless: :membership_approval_needed?, if: :pending?
  # scopes ....................................................................
  default_scope -> { pending }
  # additional config (i.e. accepts_nested_attribute_for etc...) ..............
  attribute :action, :string
  delegate :membership_approval_needed?, to: :forum
  # class methods .............................................................
  # public instance methods ...................................................
  def update_status
    return false if invalid? || !respond_to?(action)
    send("#{action}!")
  end
  # protected instance methods ................................................
  # private instance methods ..................................................

  private

  def auto_approval
    accept
  end
end
