class Forums::Preference < ApplicationRecord
  # table name ................................................................
  self.table_name = 'forum_preferences'
  # extends ...................................................................
  # includes ..................................................................
  # constants .................................................................
  # relationships .............................................................
  belongs_to :forum
  # validations ...............................................................
  validates :postable_roles, array: { inclusion: { in: Role::PERMISSIONS } }
  # callbacks .................................................................
  after_initialize :initialize_postable_roles
  # scopes ....................................................................
  # additional config (i.e. accepts_nested_attribute_for etc...) ..............
  serialize :postable_roles, Array
  encrypted_id key: 'RpfwGrdpL9KMpQ'
  # class methods .............................................................
  # public instance methods ...................................................
  # protected instance methods ................................................
  # private instance methods ..................................................

  def initialize_postable_roles
    self.postable_roles ||= []
  end
end
