class Forums::Preference < ApplicationRecord
  # table name ................................................................
  self.table_name = 'forum_preferences'
  # extends ...................................................................
  # includes ..................................................................
  # constants .................................................................
  # relationships .............................................................
  belongs_to :forum
  # validations ...............................................................
  validate :must_of_valid_roles
  # callbacks .................................................................
  # scopes ....................................................................
  # additional config (i.e. accepts_nested_attribute_for etc...) ..............
  serialize :postable_roles, Array
  encrypted_id key: 'RpfwGrdpL9KMpQ'
  # class methods .............................................................
  # public instance methods ...................................................
  # protected instance methods ................................................
  # private instance methods ..................................................

  private

  def must_of_valid_roles
    roles = Forums::Membership.roles.values
    postable_roles.each do |role|
      errors.add(:postable_roles, 'Must be right role') unless roles.include? role
    end
  end
end
