class Comment < ApplicationRecord
  # extends ...................................................................
  # includes ..................................................................
  include ActsAsLikeable::Likeable
  # constants .................................................................
  # related macros ............................................................
  # relationships .............................................................
  belongs_to :commentable, polymorphic: true, optional: true
  belongs_to :user
  has_many :comments, as: :commentable
  # validations ...............................................................
  validates :commentable, presence: true
  validates :content, presence: true
  # callbacks .................................................................
  # scopes ....................................................................
  # other macros (like devise's) ..............................................
  # class methods .............................................................
  # public instance methods ...................................................
  # protected instance methods ................................................
  # private instance methods ..................................................
end
