class Favorite < ApplicationRecord
  # extends ...................................................................
  # includes ..................................................................
  # constants .................................................................
  # related macros ............................................................
  # relationships .............................................................
  belongs_to :user
  belongs_to :favorable, polymorphic: true
  # validations ...............................................................
  validates :user_id, uniqueness: { scope: %i(favorable_id favorable_type) }
  # callbacks .................................................................
  # scopes ....................................................................
  # additional config (i.e. accepts_nested_attribute_for etc...) ..............
  encrypted_id key: 'P6jnaXZpyQBQuX'
  # class methods .............................................................
  # public instance methods ...................................................
  # protected instance methods ................................................
  # private instance methods ..................................................
end
