class Like < ApplicationRecord
  # extends ...................................................................
  # includes ..................................................................
  # constants .................................................................
  # relationships .............................................................
  belongs_to :liker, class_name: 'User', foreign_key: :user_id
  belongs_to :likeable, polymorphic: true
  # validations ...............................................................
  validates :user_id, uniqueness: { scope: %i(likeable_id likeable_type) }
  # callbacks .................................................................
  # scopes ....................................................................
  # additional config (i.e. accepts_nested_attribute_for etc...) ..............
  encrypted_id key: '9edkXgYsCQDZfB'
  # class methods .............................................................
  # public instance methods ...................................................
  # protected instance methods ................................................
  # private instance methods ..................................................
end
