class Role < ApplicationRecord
  # extends ...................................................................
  scopify
  # includes ..................................................................
  # constants .................................................................
  PERMISSIONS = %w(owner collaborator admin).freeze
  # relationships .............................................................
  has_and_belongs_to_many :users, join_table: :users_roles
  belongs_to :resource, polymorphic: true, optional: true
  # validations ...............................................................
  validates :resource_type, inclusion: { in: Rolify.resource_types }, allow_nil: true
  # callbacks .................................................................
  # scopes ....................................................................
  # additional config (i.e. accepts_nested_attribute_for etc...) ..............
  # class methods .............................................................
  # public instance methods ...................................................
  # protected instance methods ................................................
  # private instance methods ..................................................
end
